/*
 * Банк терминов для тренажёра латинской номенклатуры.
 * Термины соответствуют Международной анатомической номенклатуре (TA)
 * и сгруппированы по разделам курса нормальной анатомии.
 */

const FLASHCARDS = [
  // Остеология
  { category: 'osteology', ru: 'Кость', la: 'Os, ossis' },
  { category: 'osteology', ru: 'Позвонок', la: 'Vertebra' },
  { category: 'osteology', ru: 'Позвоночный столб', la: 'Columna vertebralis' },
  { category: 'osteology', ru: 'Атлант (I шейный позвонок)', la: 'Atlas' },
  { category: 'osteology', ru: 'Осевой позвонок (II шейный)', la: 'Axis' },
  { category: 'osteology', ru: 'Выступающий позвонок (C VII)', la: 'Vertebra prominens' },
  { category: 'osteology', ru: 'Крестец', la: 'Os sacrum' },
  { category: 'osteology', ru: 'Копчик', la: 'Os coccygis' },
  { category: 'osteology', ru: 'Ребро', la: 'Costa' },
  { category: 'osteology', ru: 'Грудина', la: 'Sternum' },
  { category: 'osteology', ru: 'Угол грудины', la: 'Angulus sterni' },
  { category: 'osteology', ru: 'Лопатка', la: 'Scapula' },
  { category: 'osteology', ru: 'Ключица', la: 'Clavicula' },
  { category: 'osteology', ru: 'Плечевая кость', la: 'Humerus' },
  { category: 'osteology', ru: 'Локтевая кость', la: 'Ulna' },
  { category: 'osteology', ru: 'Лучевая кость', la: 'Radius' },
  { category: 'osteology', ru: 'Кости запястья', la: 'Ossa carpi' },
  { category: 'osteology', ru: 'Тазовая кость', la: 'Os coxae' },
  { category: 'osteology', ru: 'Вертлужная впадина', la: 'Acetabulum' },
  { category: 'osteology', ru: 'Бедренная кость', la: 'Femur' },
  { category: 'osteology', ru: 'Надколенник', la: 'Patella' },
  { category: 'osteology', ru: 'Большеберцовая кость', la: 'Tibia' },
  { category: 'osteology', ru: 'Малоберцовая кость', la: 'Fibula' },
  { category: 'osteology', ru: 'Затылочная кость', la: 'Os occipitale' },
  { category: 'osteology', ru: 'Височная кость', la: 'Os temporale' },
  { category: 'osteology', ru: 'Клиновидная кость', la: 'Os sphenoidale' },
  { category: 'osteology', ru: 'Решётчатая кость', la: 'Os ethmoidale' },
  { category: 'osteology', ru: 'Верхняя челюсть', la: 'Maxilla' },
  { category: 'osteology', ru: 'Нижняя челюсть', la: 'Mandibula' },
  { category: 'osteology', ru: 'Подъязычная кость', la: 'Os hyoideum' },
  { category: 'osteology', ru: 'Большое затылочное отверстие', la: 'Foramen magnum' },
  { category: 'osteology', ru: 'Турецкое седло', la: 'Sella turcica' },

  // Артросиндесмология
  { category: 'arthrology', ru: 'Сустав', la: 'Articulatio' },
  { category: 'arthrology', ru: 'Суставная капсула', la: 'Capsula articularis' },
  { category: 'arthrology', ru: 'Межпозвоночный диск', la: 'Discus intervertebralis' },
  { category: 'arthrology', ru: 'Плечевой сустав', la: 'Articulatio humeri' },
  { category: 'arthrology', ru: 'Локтевой сустав', la: 'Articulatio cubiti' },
  { category: 'arthrology', ru: 'Тазобедренный сустав', la: 'Articulatio coxae' },
  { category: 'arthrology', ru: 'Коленный сустав', la: 'Articulatio genus' },
  { category: 'arthrology', ru: 'Мениск', la: 'Meniscus' },
  { category: 'arthrology', ru: 'Височно-нижнечелюстной сустав', la: 'Articulatio temporomandibularis' },
  { category: 'arthrology', ru: 'Лобковый симфиз', la: 'Symphysis pubica' },

  // Миология
  { category: 'myology', ru: 'Мышца', la: 'Musculus' },
  { category: 'myology', ru: 'Сухожилие', la: 'Tendo' },
  { category: 'myology', ru: 'Мышца, выпрямляющая позвоночник', la: 'Musculus erector spinae' },
  { category: 'myology', ru: 'Трапециевидная мышца', la: 'Musculus trapezius' },
  { category: 'myology', ru: 'Широчайшая мышца спины', la: 'Musculus latissimus dorsi' },
  { category: 'myology', ru: 'Диафрагма', la: 'Diaphragma' },
  { category: 'myology', ru: 'Прямая мышца живота', la: 'Musculus rectus abdominis' },
  { category: 'myology', ru: 'Белая линия живота', la: 'Linea alba' },
  { category: 'myology', ru: 'Паховый канал', la: 'Canalis inguinalis' },
  { category: 'myology', ru: 'Двуглавая мышца плеча', la: 'Musculus biceps brachii' },
  { category: 'myology', ru: 'Дельтовидная мышца', la: 'Musculus deltoideus' },
  { category: 'myology', ru: 'Четырёхглавая мышца бедра', la: 'Musculus quadriceps femoris' },
  { category: 'myology', ru: 'Трёхглавая мышца голени', la: 'Musculus triceps surae' },
  { category: 'myology', ru: 'Пяточное (ахиллово) сухожилие', la: 'Tendo calcaneus' },
  { category: 'myology', ru: 'Большая ягодичная мышца', la: 'Musculus gluteus maximus' },
  { category: 'myology', ru: 'Жевательная мышца', la: 'Musculus masseter' },
  { category: 'myology', ru: 'Грудино-ключично-сосцевидная мышца', la: 'Musculus sternocleidomastoideus' },

  // Спланхнология
  { category: 'splanchnology', ru: 'Полость рта', la: 'Cavitas oris' },
  { category: 'splanchnology', ru: 'Зуб', la: 'Dens' },
  { category: 'splanchnology', ru: 'Язык', la: 'Lingua' },
  { category: 'splanchnology', ru: 'Глотка', la: 'Pharynx' },
  { category: 'splanchnology', ru: 'Пищевод', la: 'Oesophagus' },
  { category: 'splanchnology', ru: 'Желудок', la: 'Gaster (Ventriculus)' },
  { category: 'splanchnology', ru: 'Двенадцатиперстная кишка', la: 'Duodenum' },
  { category: 'splanchnology', ru: 'Тощая кишка', la: 'Jejunum' },
  { category: 'splanchnology', ru: 'Подвздошная кишка', la: 'Ileum' },
  { category: 'splanchnology', ru: 'Слепая кишка', la: 'Caecum' },
  { category: 'splanchnology', ru: 'Червеобразный отросток', la: 'Appendix vermiformis' },
  { category: 'splanchnology', ru: 'Прямая кишка', la: 'Rectum' },
  { category: 'splanchnology', ru: 'Печень', la: 'Hepar' },
  { category: 'splanchnology', ru: 'Жёлчный пузырь', la: 'Vesica biliaris' },
  { category: 'splanchnology', ru: 'Поджелудочная железа', la: 'Pancreas' },
  { category: 'splanchnology', ru: 'Гортань', la: 'Larynx' },
  { category: 'splanchnology', ru: 'Трахея', la: 'Trachea' },
  { category: 'splanchnology', ru: 'Лёгкое', la: 'Pulmo' },
  { category: 'splanchnology', ru: 'Плевра', la: 'Pleura' },
  { category: 'splanchnology', ru: 'Средостение', la: 'Mediastinum' },
  { category: 'splanchnology', ru: 'Почка', la: 'Ren' },
  { category: 'splanchnology', ru: 'Мочеточник', la: 'Ureter' },
  { category: 'splanchnology', ru: 'Мочевой пузырь', la: 'Vesica urinaria' },
  { category: 'splanchnology', ru: 'Матка', la: 'Uterus' },
  { category: 'splanchnology', ru: 'Яичко', la: 'Testis' },
  { category: 'splanchnology', ru: 'Предстательная железа', la: 'Prostata' },

  // Ангиология
  { category: 'angiology', ru: 'Сердце', la: 'Cor' },
  { category: 'angiology', ru: 'Аорта', la: 'Aorta' },
  { category: 'angiology', ru: 'Дуга аорты', la: 'Arcus aortae' },
  { category: 'angiology', ru: 'Плечеголовной ствол', la: 'Truncus brachiocephalicus' },
  { category: 'angiology', ru: 'Общая сонная артерия', la: 'Arteria carotis communis' },
  { category: 'angiology', ru: 'Чревный ствол', la: 'Truncus coeliacus' },
  { category: 'angiology', ru: 'Верхняя брыжеечная артерия', la: 'Arteria mesenterica superior' },
  { category: 'angiology', ru: 'Верхняя полая вена', la: 'Vena cava superior' },
  { category: 'angiology', ru: 'Нижняя полая вена', la: 'Vena cava inferior' },
  { category: 'angiology', ru: 'Воротная вена печени', la: 'Vena portae hepatis' },
  { category: 'angiology', ru: 'Грудной проток', la: 'Ductus thoracicus' },
  { category: 'angiology', ru: 'Венечные (коронарные) артерии сердца', la: 'Arteriae coronariae cordis' },

  // Неврология
  { category: 'neurology', ru: 'Спинной мозг', la: 'Medulla spinalis' },
  { category: 'neurology', ru: 'Головной мозг', la: 'Encephalon' },
  { category: 'neurology', ru: 'Продолговатый мозг', la: 'Medulla oblongata' },
  { category: 'neurology', ru: 'Мост', la: 'Pons' },
  { category: 'neurology', ru: 'Средний мозг', la: 'Mesencephalon' },
  { category: 'neurology', ru: 'Мозжечок', la: 'Cerebellum' },
  { category: 'neurology', ru: 'Промежуточный мозг', la: 'Diencephalon' },
  { category: 'neurology', ru: 'Таламус', la: 'Thalamus' },
  { category: 'neurology', ru: 'Гипоталамус', la: 'Hypothalamus' },
  { category: 'neurology', ru: 'Конечный мозг', la: 'Telencephalon' },
  { category: 'neurology', ru: 'Твёрдая оболочка мозга', la: 'Dura mater' },
  { category: 'neurology', ru: 'Паутинная оболочка', la: 'Arachnoidea mater' },
  { category: 'neurology', ru: 'Мягкая оболочка', la: 'Pia mater' },
  { category: 'neurology', ru: 'Спинномозговая жидкость', la: 'Liquor cerebrospinalis' },
  { category: 'neurology', ru: 'Плечевое сплетение', la: 'Plexus brachialis' },
  { category: 'neurology', ru: 'Седалищный нерв', la: 'Nervus ischiadicus' },
  { category: 'neurology', ru: 'Тройничный нерв', la: 'Nervus trigeminus' },
  { category: 'neurology', ru: 'Лицевой нерв', la: 'Nervus facialis' },
  { category: 'neurology', ru: 'Блуждающий нерв', la: 'Nervus vagus' },
  { category: 'neurology', ru: 'Симпатический ствол', la: 'Truncus sympathicus' },

  // Органы чувств
  { category: 'sense-organs', ru: 'Глазное яблоко', la: 'Bulbus oculi' },
  { category: 'sense-organs', ru: 'Роговица', la: 'Cornea' },
  { category: 'sense-organs', ru: 'Сетчатка', la: 'Retina' },
  { category: 'sense-organs', ru: 'Хрусталик', la: 'Lens' },
  { category: 'sense-organs', ru: 'Барабанная перепонка', la: 'Membrana tympani' },
  { category: 'sense-organs', ru: 'Улитка', la: 'Cochlea' },
  { category: 'sense-organs', ru: 'Кожа', la: 'Cutis' },
  { category: 'sense-organs', ru: 'Эпидермис', la: 'Epidermis' }
];

const FLASHCARD_CATEGORIES = [
  { id: 'all', title: 'Все темы', icon: '🗂️' },
  { id: 'osteology', title: 'Остеология', icon: '🦴' },
  { id: 'arthrology', title: 'Артросиндесмология', icon: '🔗' },
  { id: 'myology', title: 'Миология', icon: '💪' },
  { id: 'splanchnology', title: 'Спланхнология', icon: '🫁' },
  { id: 'angiology', title: 'Ангиология', icon: '❤️' },
  { id: 'neurology', title: 'Неврология', icon: '🧠' },
  { id: 'sense-organs', title: 'Органы чувств', icon: '👁️' }
];
